[theme]
# Primary accent color for interactive elements.
primaryColor = "#f3c762"

# Background color for the main content area.
backgroundColor = "#20234c"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#232121"

# Color used for almost all text.
textColor = "#f3c762"